SET LINESIZE 		100
SET PAGESIZE 		300

DROP TABLE Applies PURGE;
DROP TABLE SNeeded PURGE;
DROP TABLE Position PURGE;
DROP TABLE SPossessed PURGE;
DROP TABLE CoursePassed PURGE;
DROP TABLE FEmployer PURGE;
DROP TABLE Referee PURGE;
DROP TABLE Applicant PURGE;
DROP TABLE LPTitle PURGE;
DROP TABLE LState PURGE;
DROP TABLE LSkill PURGE;

PROMPT Done.
